# Lambda-Ping Serverless Definition.

service: ping

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10

  # As we save metrics to CloudWatch, we need to grant this Lambda the rights to
  # public metric data. IAM for CloudWatch metrics doesn't offer the ability to
  # limit the resource scope to a specific NameSpace (sadly)
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "cloudwatch:PutMetricData"
      Resource: "*"

# We only have the one function. In future we may add others, eg new protocol
# support if ICMP ever becomes possible on Lambda.
functions:
  http:
    handler: handler.http
    description: "Perform an HTTP request to 'ping' a remote server to determine availablity"
    memorySize: 128 # MB
    timeout: 30 # seconds
